version: "2"
services:
  node:
    image: "node"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "80:8081"
    command: "npm --registry https://registry.npm.taobao.org install --global babel"
    command: "npm --registry https://registry.npm.taobao.org install express --save"
    command: "babel src --out-dir build"
    command: "npm start"
