version: '3'
services:
  mysql:
      image: mysql
      restart: always
      ports: 
        - 30000:3306
      environment:
        MYSQL_ROOT_PASSWORD: prisma
      volumes:
        - mysql:/var/lib/mysql
volumes:
  mysql:
