# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - 10002:10002
    environment:
      MYSQL_ROOT_PASSWORD: snake1
